#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : tiptop
Version  : 2.3
Release  : 8
URL      : http://tiptop.gforge.inria.fr/releases/tiptop-2.3.tar.gz
Source0  : http://tiptop.gforge.inria.fr/releases/tiptop-2.3.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: tiptop-bin
Requires: tiptop-doc
BuildRequires : bison
BuildRequires : flex
BuildRequires : libxml2-dev
BuildRequires : ncurses-dev

%description
Tiptop
Tiptop is a performance monitoring tool for Linux.  It provides a
dynamic real-time view of the tasks running in the system. Tiptop is
very similar to the top utility, but most of the information displayed
comes from hardware counters.

%package bin
Summary: bin components for the tiptop package.
Group: Binaries

%description bin
bin components for the tiptop package.


%package doc
Summary: doc components for the tiptop package.
Group: Documentation

%description doc
doc components for the tiptop package.


%prep
%setup -q -n tiptop-2.3

%build
%configure --disable-static
make V=1  %{?_smp_mflags}

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/ptiptop
/usr/bin/tiptop

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*
