#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : tiptop
Version  : 2.3.1
Release  : 24
URL      : https://files.inria.fr/pacap/tiptop/tiptop-2.3.1.tar.gz
Source0  : https://files.inria.fr/pacap/tiptop/tiptop-2.3.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: tiptop-bin = %{version}-%{release}
Requires: tiptop-license = %{version}-%{release}
Requires: tiptop-man = %{version}-%{release}
BuildRequires : bison
BuildRequires : flex
BuildRequires : libxml2-dev
BuildRequires : ncurses-dev
Patch1: timestamp.patch

%description
Tiptop
Tiptop is a performance monitoring tool for Linux.  It provides a
dynamic real-time view of the tasks running in the system. Tiptop is
very similar to the top utility, but most of the information displayed
comes from hardware counters.

%package bin
Summary: bin components for the tiptop package.
Group: Binaries
Requires: tiptop-license = %{version}-%{release}

%description bin
bin components for the tiptop package.


%package license
Summary: license components for the tiptop package.
Group: Default

%description license
license components for the tiptop package.


%package man
Summary: man components for the tiptop package.
Group: Default

%description man
man components for the tiptop package.


%prep
%setup -q -n tiptop-2.3.1
cd %{_builddir}/tiptop-2.3.1
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1657564935
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
%configure --disable-static
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1657564935
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/tiptop
cp %{_builddir}/tiptop-2.3.1/COPYING %{buildroot}/usr/share/package-licenses/tiptop/4cc77b90af91e615a64ae04893fdffa7939db84c
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/ptiptop
/usr/bin/tiptop

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/tiptop/4cc77b90af91e615a64ae04893fdffa7939db84c

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/ptiptop.1
/usr/share/man/man1/tiptop.1
